services:
  backend:
    build: ./backend
    container_name: bank-backend
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: bank-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend